<div class="order-track-wrapper">
    <div id="order-track-dialog">
        <div id="order-track-map"></div>
    </div>
    <script type="text/x-magento-init">
      {
        "#order-track-dialog": {
          "mapbox": {
            "accessToken": "pk.eyJ1IjoiZGVidWdnZXJ5YW5nIiwiYSI6ImNraTA4ZmpzOTFiYmIycXRob2wxajlwOW8ifQ.8qdYPNJ_YnIExDIdleL5Eg",
            "destination": "3-7 Souter St, Beaconsfield VIC 3807 Australia",
            "from": "1341 Dandenong Road Chadstone VIC 3148 Australia"
          }
        }
      }
    </script>

</div>